language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
install:
  - "npm install"
script:
  - "./node_modules/eslint/bin/eslint.js --format 'node_modules/eslint-friendly-formatter' src test"
  - "./node_modules/.bin/nyc --require babel-core/register --all ./node_modules/.bin/mocha && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
cache:
  directories:
    - node_modules
